baseURL = "https://links.gardlt.io/"
languageCode = "en"
defaultContentLanguage = "en"
theme = "lynx"
title = "Potato Traveler"
enableEmoji = true
disableKinds = ["taxonomy", "term"]
googleAnalytics = "G-4WR14R1NLK"
copyright = "Copyright German Rivera De La Torre"

[params.author]
  name = "Potato Traveler"
  headline = "Photographer | Videographer | Software"
  image = "author.jpeg"
  links = [
    { link = { href = "http://portfolio.gardlt.io/work/", text = "Portfolio", icon = "camera-retro-solid" } },
    { instagram = "https://instagram.com/potato.traveler/" },
    { link = { href = "https://unsplash.com/@potato_traveler", text = "Unsplash", icon = "unsplash" } },
    { link = { href = "https://pixabay.com/users/potato_traveler-14397780/", text = "Pixabay", icon = "unsplash" } },
    { email = "mailto:potatotraveler@gmail.com" },
    { twitter = "https://twitter.com/traveler_potato" },
    { link = { href = "http://blog.gardlt.io/", text = "Blog", icon = "blogger" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"